### ISSUE TITLE
Baam

### ISSUE THREAD

**Issue by blaggacao** [xoe-labs/dodoo#2]
@em92 A new fun project with little tools that shine! :wink: (check `dodoo-run`)

**Comment by em92** [comment]
The only thing I understood what it does - adds /metrics endpoint to odoo. Also didn't understand usecases.

**Comment by blaggacao** [comment]
In very general terms it tries to suck less than odoo. More specifically, it wraps up all that's (from my experience) bad in running odoo and needed improvement. And last but not least, it's a project to improve skills on a lot of interesting things.

One day I should do a proper write-up in an OOEP. ;-)

A qucklist, though:
- graphql endpoint (maybe somewhat asybc)
- metrics
- microservices architecture
- Client Session
- Dev-Certs
- advanced odoo-specific reloader (not sure though if that will make it into final, it's a bit hacky)
- hackable and we'll structured - maybe the most important thing
- maybe: matrix application service for odoo chat.
- + all what `dodoo` itself does (better logging, patching bad odoo, hot reload config, manage secrets securely, better db config options).
