### ISSUE TITLE
What Odoo versions are supported?

### ISSUE THREAD

**Issue by agb80** [xoe-labs/dodoo#3]
Just as the title said...

## Checklist

- [x] I have searched the [issues](https://github.com/xoe-labs/dodoo/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://github.com/xoe-labs/dodoo#readme) and believe that my question is not covered.

**Comment by blaggacao** [comment]
@agb80 Hi!

Thanks for your interest. Unfortunately, this project is stale.

If you have interest or know somebody who has interest in taking maintainership, please feel free to fork and let me know so I can archive this repo and forward to such fork in the readme.

Cheers!

**Comment by agb80** [comment]
Thank you for your answer.
